<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="EP-CP-102" name="travelProduct.TravelProductJourney" tests="14" failures="1" timestamp="17 Jul 2017 06:39:13 GMT" time="127.339" errors="0">
  <testcase name="CustomerProceed" time="0.365" classname="travelProduct.TravelProductJourney"/>
  <testcase name="CustomerMobno" time="0.156" classname="travelProduct.TravelProductJourney"/>
  <testcase name="LaunchWebsite" time="6.974" classname="travelProduct.TravelProductJourney"/>
  <testcase name="JourneyStartDate" time="6.310" classname="travelProduct.TravelProductJourney"/>
  <testcase name="NoofTravellers" time="1.089" classname="travelProduct.TravelProductJourney"/>
  <testcase name="memberage" time="2.160" classname="travelProduct.TravelProductJourney"/>
  <testcase name="ContinueButton" time="1.165" classname="travelProduct.TravelProductJourney"/>
  <testcase name="CustomerEmail" time="0.222" classname="travelProduct.TravelProductJourney"/>
  <testcase name="GetLiveQuotes" time="10.501" classname="travelProduct.TravelProductJourney"/>
  <testcase name="FillLoginDetails" time="18.807" classname="travelProduct.TravelProductJourney"/>
  <testcase name="destinationcountry" time="5.933" classname="travelProduct.TravelProductJourney"/>
  <testcase name="QuotesBuyNow" time="71.067" classname="travelProduct.TravelProductJourney">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at travelProduct.TravelProductJourney.CustomerEmail(TravelProductJourney.java:356)
	at travelProduct.TravelProductJourney.QuotesBuyNow(TravelProductJourney.java:424)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- QuotesBuyNow -->
  <testcase name="CustomerPopup" time="0.266" classname="travelProduct.TravelProductJourney"/>
  <testcase name="JourneyEndDate" time="2.324" classname="travelProduct.TravelProductJourney"/>
</testsuite> <!-- travelProduct.TravelProductJourney -->
